- name: Downloading composer.phar
  get_url:
    url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
    dest: "/usr/local/bin/composer"
    checksum: "{{ composer_checksum | default(None) }}"
    owner: root
    group: root
    mode: 0755
