---
- name: Converge
  hosts: all
  become: yes
  vars:
    php_enabled: yes
    php_version: 7.2

    composer_user: vagrant
    composer_app_path: /home/vagrant

  roles:
    - role: blunix.role-php
    - role: role-composer
